// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(QuanLyThuVienContext))]
    [Migration("20260114022428_AddNewModelsMigration")]
    partial class AddNewModelsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.CtPhieuMuon", b =>
                {
                    b.Property<int>("PhieuMuonId")
                        .HasColumnType("int");

                    b.Property<int>("SachId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayTraThucTe")
                        .HasColumnType("date");

                    b.Property<string>("TinhTrangLucMuon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrangLucTra")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PhieuMuonId", "SachId");

                    b.HasIndex("SachId");

                    b.ToTable("CT_PhieuMuon", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.CtPhieuTra", b =>
                {
                    b.Property<int>("PhieuTraId")
                        .HasColumnType("int");

                    b.Property<int>("SachId")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrangLucTra")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PhieuTraId", "SachId");

                    b.HasIndex("SachId");

                    b.ToTable("CT_PhieuTra", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DauSach", b =>
                {
                    b.Property<int>("DauSachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DauSachId"));

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("NgonNgu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NhaXuatBanId")
                        .HasColumnType("int");

                    b.Property<int?>("TheLoaiId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DauSachId")
                        .HasName("PK__DauSach__93F51B8B40651502");

                    b.HasIndex("NhaXuatBanId");

                    b.HasIndex("TheLoaiId");

                    b.HasIndex(new[] { "Isbn" }, "UQ__DauSach__447D36EA39162874")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("DauSach", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DauSachTacGium", b =>
                {
                    b.Property<int>("DauSachId")
                        .HasColumnType("int");

                    b.Property<int>("TacGiaId")
                        .HasColumnType("int");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DauSachId", "TacGiaId");

                    b.HasIndex("TacGiaId");

                    b.ToTable("DauSach_TacGia", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DocGium", b =>
                {
                    b.Property<int>("DocGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocGiaId"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("DocGiaId")
                        .HasName("PK__DocGia__E34FB53CB8ECFA18");

                    b.ToTable("DocGia");
                });

            modelBuilder.Entity("WebApplication1.Models.NhaXuatBan", b =>
                {
                    b.Property<int>("NhaXuatBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhaXuatBanId"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNxb")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenNXB");

                    b.HasKey("NhaXuatBanId")
                        .HasName("PK__NhaXuatB__E0587C0ED1135116");

                    b.ToTable("NhaXuatBan", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Phat", b =>
                {
                    b.Property<int>("PhatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhatId"));

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("PhieuMuonId")
                        .HasColumnType("int");

                    b.Property<int?>("SachId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PhatId")
                        .HasName("PK__Phat__F2A5F66BEE7A7B09");

                    b.HasIndex("PhieuMuonId");

                    b.HasIndex("SachId");

                    b.ToTable("Phat", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.PhieuMuon", b =>
                {
                    b.Property<int>("PhieuMuonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuMuonId"));

                    b.Property<int>("DocGiaId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("HanTra")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Đang mượn");

                    b.HasKey("PhieuMuonId")
                        .HasName("PK__PhieuMuo__172705F19D7672D1");

                    b.HasIndex("DocGiaId");

                    b.ToTable("PhieuMuon", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.PhieuTra", b =>
                {
                    b.Property<int>("PhieuTraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuTraId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("PhieuMuonId")
                        .HasColumnType("int");

                    b.HasKey("PhieuTraId")
                        .HasName("PK__PhieuTra__35C6280D5F4EA923");

                    b.HasIndex("PhieuMuonId");

                    b.ToTable("PhieuTra", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Sach", b =>
                {
                    b.Property<int>("SachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SachId"));

                    b.Property<int>("DauSachId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaVach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Có sẵn");

                    b.Property<string>("ViTriKe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SachId")
                        .HasName("PK__Sach__F3005E1A548AA6F7");

                    b.HasIndex("DauSachId");

                    b.HasIndex(new[] { "MaVach" }, "UQ__Sach__8BBF4A1C92D9ED94")
                        .IsUnique();

                    b.ToTable("Sach", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.TacGium", b =>
                {
                    b.Property<int>("TacGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TacGiaId"));

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TacGiaId")
                        .HasName("PK__TacGia__E80231298F259433");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("WebApplication1.Models.ThanhToanPhat", b =>
                {
                    b.Property<int>("ThanhToanPhatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanPhatId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("PhatId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ThanhToanPhatId")
                        .HasName("PK__ThanhToa__64EA6A2C9CA4FFC4");

                    b.HasIndex("PhatId");

                    b.ToTable("ThanhToanPhat", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.TheLoai", b =>
                {
                    b.Property<int>("TheLoaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheLoaiId"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TheLoaiId")
                        .HasName("PK__TheLoai__241C3B1A59FB06B8");

                    b.ToTable("TheLoai", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.CtPhieuMuon", b =>
                {
                    b.HasOne("WebApplication1.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("CtPhieuMuons")
                        .HasForeignKey("PhieuMuonId")
                        .IsRequired()
                        .HasConstraintName("FK_CTPM_PhieuMuon");

                    b.HasOne("WebApplication1.Models.Sach", "Sach")
                        .WithMany("CtPhieuMuons")
                        .HasForeignKey("SachId")
                        .IsRequired()
                        .HasConstraintName("FK_CTPM_Sach");

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("WebApplication1.Models.CtPhieuTra", b =>
                {
                    b.HasOne("WebApplication1.Models.PhieuTra", "PhieuTra")
                        .WithMany("CtPhieuTras")
                        .HasForeignKey("PhieuTraId")
                        .IsRequired()
                        .HasConstraintName("FK_CTPT_PhieuTra");

                    b.HasOne("WebApplication1.Models.Sach", "Sach")
                        .WithMany("CtPhieuTras")
                        .HasForeignKey("SachId")
                        .IsRequired()
                        .HasConstraintName("FK_CTPT_Sach");

                    b.Navigation("PhieuTra");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("WebApplication1.Models.DauSach", b =>
                {
                    b.HasOne("WebApplication1.Models.NhaXuatBan", "NhaXuatBan")
                        .WithMany("DauSaches")
                        .HasForeignKey("NhaXuatBanId")
                        .HasConstraintName("FK_DauSach_NhaXuatBan");

                    b.HasOne("WebApplication1.Models.TheLoai", "TheLoai")
                        .WithMany("DauSaches")
                        .HasForeignKey("TheLoaiId")
                        .HasConstraintName("FK_DauSach_TheLoai");

                    b.Navigation("NhaXuatBan");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("WebApplication1.Models.DauSachTacGium", b =>
                {
                    b.HasOne("WebApplication1.Models.DauSach", "DauSach")
                        .WithMany("DauSachTacGia")
                        .HasForeignKey("DauSachId")
                        .IsRequired()
                        .HasConstraintName("FK_DSTG_DauSach");

                    b.HasOne("WebApplication1.Models.TacGium", "TacGia")
                        .WithMany("DauSachTacGia")
                        .HasForeignKey("TacGiaId")
                        .IsRequired()
                        .HasConstraintName("FK_DSTG_TacGia");

                    b.Navigation("DauSach");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("WebApplication1.Models.Phat", b =>
                {
                    b.HasOne("WebApplication1.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("Phats")
                        .HasForeignKey("PhieuMuonId")
                        .IsRequired()
                        .HasConstraintName("FK_Phat_PhieuMuon");

                    b.HasOne("WebApplication1.Models.Sach", "Sach")
                        .WithMany("Phats")
                        .HasForeignKey("SachId")
                        .HasConstraintName("FK_Phat_Sach");

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("WebApplication1.Models.PhieuMuon", b =>
                {
                    b.HasOne("WebApplication1.Models.DocGium", "DocGia")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("DocGiaId")
                        .IsRequired()
                        .HasConstraintName("FK_PhieuMuon_DocGia");

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("WebApplication1.Models.PhieuTra", b =>
                {
                    b.HasOne("WebApplication1.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("PhieuTras")
                        .HasForeignKey("PhieuMuonId")
                        .IsRequired()
                        .HasConstraintName("FK_PhieuTra_PhieuMuon");

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("WebApplication1.Models.Sach", b =>
                {
                    b.HasOne("WebApplication1.Models.DauSach", "DauSach")
                        .WithMany("Saches")
                        .HasForeignKey("DauSachId")
                        .IsRequired()
                        .HasConstraintName("FK_Sach_DauSach");

                    b.Navigation("DauSach");
                });

            modelBuilder.Entity("WebApplication1.Models.ThanhToanPhat", b =>
                {
                    b.HasOne("WebApplication1.Models.Phat", "Phat")
                        .WithMany("ThanhToanPhats")
                        .HasForeignKey("PhatId")
                        .IsRequired()
                        .HasConstraintName("FK_ThanhToanPhat_Phat");

                    b.Navigation("Phat");
                });

            modelBuilder.Entity("WebApplication1.Models.DauSach", b =>
                {
                    b.Navigation("DauSachTacGia");

                    b.Navigation("Saches");
                });

            modelBuilder.Entity("WebApplication1.Models.DocGium", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("WebApplication1.Models.NhaXuatBan", b =>
                {
                    b.Navigation("DauSaches");
                });

            modelBuilder.Entity("WebApplication1.Models.Phat", b =>
                {
                    b.Navigation("ThanhToanPhats");
                });

            modelBuilder.Entity("WebApplication1.Models.PhieuMuon", b =>
                {
                    b.Navigation("CtPhieuMuons");

                    b.Navigation("Phats");

                    b.Navigation("PhieuTras");
                });

            modelBuilder.Entity("WebApplication1.Models.PhieuTra", b =>
                {
                    b.Navigation("CtPhieuTras");
                });

            modelBuilder.Entity("WebApplication1.Models.Sach", b =>
                {
                    b.Navigation("CtPhieuMuons");

                    b.Navigation("CtPhieuTras");

                    b.Navigation("Phats");
                });

            modelBuilder.Entity("WebApplication1.Models.TacGium", b =>
                {
                    b.Navigation("DauSachTacGia");
                });

            modelBuilder.Entity("WebApplication1.Models.TheLoai", b =>
                {
                    b.Navigation("DauSaches");
                });
#pragma warning restore 612, 618
        }
    }
}
